# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cf6e7eafd4743e814f20826173b776289002a404dfefc53528af46d434e3b71aa0e21bebb226e57db0e2cb11d577cec3ca5d163da983ee5e650f3ca7de2345d

test:
  secret_key_base: 9234707d2c7a93ebe12db1fe5ccdb5eecd6e334d21152b35c61b618e7a697b4d3c4abe319b70f5077d1ca04679e1aeaff8860ae2a447b6adba2bdf11700ec55a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
